"""Golden test: every seeded mission gets its expected decision and cites its concepts (spec §7).

It also checks that docs/data/seeded.json is the current generated result.
"""

import json
from pathlib import Path

import pytest
import yaml
from jsonschema import Draft202012Validator
from seeded import run_all

ROOT = Path(__file__).resolve().parents[1]
SEEDED = ROOT / "missions" / "SEEDED.yaml"
ENTRIES = yaml.safe_load(SEEDED.read_text())
SCHEMA = json.loads((ROOT / "tests" / "fixtures" / "qgc" / "plan.schema.json").read_text())


@pytest.fixture(scope="module")
def run(tmp_path_factory) -> tuple[dict, Path]:
    out = tmp_path_factory.mktemp("out")
    return run_all(SEEDED, ROOT / "knowledge", ROOT / "tools.lock", out), out


def test_every_mission_file_is_seeded() -> None:
    files = {p.stem for p in (ROOT / "missions").glob("*.yaml")} - {"SEEDED"}
    assert files == {e["mission"] for e in ENTRIES}


@pytest.mark.parametrize("entry", ENTRIES, ids=lambda e: e["mission"])
def test_seeded_decision_and_citations(run, entry: dict) -> None:
    doc, _ = run
    result = next(m for m in doc["missions"] if m["mission"] == entry["mission"])
    assert result["decision"] == entry["expected"]
    assert set(entry.get("cites", [])) <= {f["concept_id"] for f in result["fails"]}
    assert set(entry.get("gaps", [])) <= {g["check_id"] for g in result["gaps"]}


@pytest.mark.parametrize("entry", ENTRIES, ids=lambda e: e["mission"])
def test_seeded_plan_validates_against_the_subset_schema(run, entry: dict) -> None:
    _, out = run
    plan = json.loads((out / entry["mission"] / "mission.plan").read_text())
    assert list(Draft202012Validator(SCHEMA).iter_errors(plan)) == []


def test_published_results_are_current(run) -> None:
    """docs/data/seeded.json is generated by `make seeded`; it must match a fresh run."""
    doc, _ = run
    assert json.loads((ROOT / "docs" / "data" / "seeded.json").read_text()) == doc
